/**
 * Generates `supabase/seed.sql` (spec §9): 3 events, ~40 people with a mix of umich
 * and gmail addresses, one pair that must land in the review queue as an ambiguous
 * match, 5 V1 members, Slack channels and activity, coffee chats, and the admin row
 * from SEED_ADMIN_EMAIL.
 *
 * Deterministic on purpose: a seeded RNG and a fixed base date, so re-running
 * produces byte-identical SQL and the checked-in file is stable. No faker.
 *
 *   pnpm seed:generate            # writes supabase/seed.sql if it does not exist
 *   pnpm seed:generate -- --force # overwrite
 */
import { createHash } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';

try { process.loadEnvFile('.env'); } catch { /* env may come from the shell */ }

const OUT = 'supabase/seed.sql';
const BASE = new Date('2026-09-01T12:00:00Z'); // fixed: the output must not drift daily
const ADMIN = process.env.SEED_ADMIN_EMAIL || 'owen@umich.edu';

/** mulberry32 — 6 lines of seeded PRNG beats a dependency. */
function rng(seed: number) {
  return () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(20260909);
const pick = <T>(xs: readonly T[]): T => xs[Math.floor(rand() * xs.length)]!;
const int = (lo: number, hi: number) => lo + Math.floor(rand() * (hi - lo + 1));

/** Stable uuid from a label, so ids do not churn between runs. */
const uuid = (label: string) => {
  const h = createHash('sha256').update(label).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};

const q = (v: unknown) =>
  v === null || v === undefined ? 'null'
    : typeof v === 'number' || typeof v === 'boolean' ? String(v)
      : `'${String(v).replaceAll("'", "''")}'`;
const day = (offset: number) =>
  new Date(BASE.getTime() + offset * 86_400_000).toISOString().slice(0, 10);
const ts = (offset: number) => new Date(BASE.getTime() + offset * 86_400_000).toISOString();

const FIRST = ['Ava', 'Noah', 'Maya', 'Leo', 'Priya', 'Diego', 'Chloe', 'Omar', 'Grace', 'Ethan',
  'Lila', 'Marcus', 'Sofia', 'Jonas', 'Nina', 'Theo', 'Ruby', 'Kai', 'Elena', 'Sam'] as const;
const LAST = ['Nguyen', 'Patel', 'Garcia', 'Kim', 'Okafor', 'Rossi', 'Chen', 'Ahmed', 'Novak',
  'Silva', 'Weber', 'Dubois', 'Haddad', 'Larsen', 'Costa', 'Ito', 'Brennan', 'Vargas'] as const;
const MAJORS = ['Computer Science', 'Business Administration', 'Mechanical Engineering',
  'Economics', 'Information', 'Data Science', 'Industrial Design'] as const;
const GENDERS = ['male', 'female', 'non_binary', 'prefer_not_to_say', null] as const;

interface Seeded { id: string; first: string; last: string; email: string; umich: boolean; member: boolean; slack: string | null }

const people: Seeded[] = [];
const used = new Set<string>();

function makePerson(first: string, last: string, umich: boolean, tag: string): Seeded {
  let local = umich ? `${first[0]!.toLowerCase()}${last.toLowerCase()}` : `${first.toLowerCase()}.${last.toLowerCase()}`;
  while (used.has(local)) local += String(used.size % 10);
  used.add(local);
  return {
    id: uuid(`person:${tag}`),
    first, last,
    email: `${local}@${umich ? 'umich.edu' : 'gmail.com'}`,
    umich,
    member: false,
    slack: null,
  };
}

for (let i = 0; i < 40; i += 1) {
  const p = makePerson(pick(FIRST), pick(LAST), rand() < 0.8, `p${i}`);
  p.member = i < 5;                       // 5 V1 members, so the member role is testable
  p.slack = i < 12 ? `U${String(i).padStart(3, '0')}SEED` : null;
  people.push(p);
}

// The deliberate ambiguity (§9): same name, different domains, no shared uniqname.
// Any name-only match against these two must land in the review queue, not auto-link.
const twinA = makePerson('Jordan', 'Bailey', true, 'twin-a');
const twinB = makePerson('Jordan', 'Bailey', false, 'twin-b');
people.push(twinA, twinB);

const events = [
  { id: uuid('event:kickoff'), name: '[F26] Kickoff', date: day(4), type: 'social', location: 'Ross B0570' },
  { id: uuid('event:open-house'), name: 'F26 Open House', date: day(18), type: 'social', location: 'Duderstadt' },
  { id: uuid('event:speaker'), name: 'Founder Fireside: Seed to Series A', date: day(32), type: 'speaker', location: 'Ross R0210' },
];

const channels = [
  { id: 'C0SEEDGEN', name: 'general' },
  { id: 'C0SEEDPRJ', name: 'projects' },
  { id: 'C0SEEDEVT', name: 'events' },
];

const lines: string[] = [
  '-- Generated by scripts/generate-seed.ts. Do not edit by hand: run `pnpm seed:generate -- --force`.',
  `-- Deterministic (seeded RNG, base date ${BASE.toISOString().slice(0, 10)}).`,
  '',
];
const insert = (table: string, cols: string[], rows: unknown[][], conflict: string) => {
  if (!rows.length) return;
  lines.push(`insert into ${table} (${cols.join(', ')}) values`);
  lines.push(rows.map((r) => `  (${r.map(q).join(', ')})`).join(',\n'));
  lines.push(`${conflict};`, '');
};

insert('events', ['id', 'name', 'event_date', 'event_type', 'location'],
  events.map((e) => [e.id, e.name, e.date, e.type, e.location]),
  'on conflict (name, event_date) do nothing');

insert('people',
  ['id', 'first_name', 'last_name', 'uniqname', 'grad_year', 'student_level', 'major', 'gender',
    'is_v1_member', 'member_since', 'slack_user_id', 'slack_joined_at'],
  people.map((p) => [
    p.id, p.first, p.last,
    p.umich ? p.email.split('@')[0] : null,
    int(2027, 2030), 'undergrad', pick(MAJORS), pick(GENDERS),
    p.member, p.member ? day(-int(30, 400)) : null,
    p.slack, p.slack ? ts(-int(1, 300)) : null,
  ]),
  'on conflict (id) do nothing');

insert('person_emails', ['id', 'person_id', 'email', 'email_normalized', 'is_primary', 'source'],
  // Generated addresses are already in normal form (lowercase, no dots in the umich
  // local part, no +tag), so email_normalized is the address itself.
  people.map((p) => [uuid(`email:${p.id}`), p.id, p.email, p.email.toLowerCase(), true, 'manual_csv']),
  'on conflict (email_normalized) do nothing');

const attendance: unknown[][] = [];
for (const e of events) {
  for (const p of people) {
    const roll = rand();
    if (roll > 0.65) continue;                       // not at this event
    const registered = roll < 0.5;
    const checkedIn = roll < 0.35 || (!registered && roll < 0.6); // walk-ins are the norm
    attendance.push([
      uuid(`att:${e.id}:${p.id}`), e.id, p.id,
      registered, registered ? `${e.date}T14:00:00Z` : null, registered ? 'luma_csv' : null,
      checkedIn, checkedIn ? `${e.date}T18:${String(int(0, 59)).padStart(2, '0')}:00Z` : null,
      checkedIn ? 'tally_csv' : null,
    ]);
  }
}
insert('event_attendance',
  ['id', 'event_id', 'person_id', 'registered', 'registered_at', 'registration_source',
    'checked_in', 'checked_in_at', 'checkin_source'],
  attendance, 'on conflict (event_id, person_id) do nothing');

insert('slack_channels', ['id', 'name', 'is_private', 'is_archived', 'bot_is_member'],
  channels.map((c) => [c.id, c.name, false, false, true]),
  'on conflict (id) do nothing');

const activity: unknown[][] = [];
for (const p of people.filter((x) => x.slack)) {
  for (const c of channels) {
    for (let d = 1; d <= 30; d += 1) {
      if (rand() > 0.18) continue;
      activity.push([p.id, c.id, day(-d), int(1, 9)]);
    }
  }
}
insert('slack_channel_activity', ['person_id', 'channel_id', 'activity_date', 'message_count'],
  activity, 'on conflict (person_id, channel_id, activity_date) do nothing');

const chats: unknown[][] = [];
const members = people.filter((p) => p.member);
for (const p of people.slice(10, 26)) {
  const m = pick(members);
  if (m.id === p.id) continue;
  chats.push([uuid(`chat:${p.id}`), p.id, m.id, day(-int(1, 60)), null, 'manual']);
}
insert('coffee_chats', ['id', 'person_id', 'member_id', 'chatted_on', 'notes', 'source'],
  chats, 'on conflict (person_id, member_id, chatted_on) do nothing');

insert('app_users', ['email', 'role'], [[ADMIN, 'admin']], 'on conflict (email) do nothing');

if (existsSync(OUT) && !process.argv.includes('--force')) {
  console.log(`${OUT} already exists; refusing to overwrite. Re-run with --force.`);
  process.exit(0);
}
writeFileSync(OUT, `${lines.join('\n')}\n`);
console.log(
  `wrote ${OUT}: ${people.length} people, ${events.length} events, ${attendance.length} attendance,`,
  `${activity.length} slack activity rows, ${chats.length} coffee chats, admin ${ADMIN}`,
);
